[book]
title = "PACT Documentation"
description = "Promise-based configuration management and admin operations for HPC/AI infrastructure"
authors = ["witlox"]
language = "en"
src = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/witlox/pact"
edit-url-template = "https://github.com/witlox/pact/edit/main/{path}"
